services:
  - type: web
    name: macrocutie
    env: node
    plan: free
    nodeVersion: 20.19.0
    buildCommand: rm -rf node_modules && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
